// THIS IS SAMPLE CODE
module.exports = {
  USERS: 'USERS',
  INSERT: {
    SUCCESS: 'DATA INSERT SUCCESSFULLY!',
    ERROR: 'DATA INSERT IS NOT SUCCESS',
  },
  GET: {
    SUCCESS: 'DATA FETCHED SUCCESSFULLY!',
    ERROR: 'ERROR WITH FETCHING DATA',
    NOTFOUND: '404 - DATA NOT FOUND!',
  },
  UPDATE: {
    SUCCESS: 'DATA UPDATE SUCCESSFULLY',
    ERROR: 'ERROR WITH UPDATE DATA',
    NOTFOUND: '404 - DATA TO UPDATE IS NOT FOUND!',
  },
  DELETE: {
    SUCCESS: 'DATA DELETED SUCCESSFULLY',
    ERROR: 'ERROR WITH DELETE DATA',
    NOTFOUND: '404 - DATA TO DELETE IS NOT FOUND!',
  },
};
